//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleCity {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleCity.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BigWall {
            get {
                object obj = ResourceManager.GetObject("BigWall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bullet {
            get {
                object obj = ResourceManager.GetObject("Bullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dog {
            get {
                object obj = ResourceManager.GetObject("Dog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Enemy {
            get {
                object obj = ResourceManager.GetObject("Enemy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Heart {
            get {
                object obj = ResourceManager.GetObject("Heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 10
        ///##################
        ///#             #  #
        ///#    P        ####
        ///#                #
        ///#  ###     ##   ##
        ///#    #      #    #
        ///#    #      #    #
        ///#    #    ########
        ///#    #      #    #
        ///#    #      #    #
        ///#    #           #
        ///###########      #
        ///#   #        #####
        ///#   #   #        #
        ///#                #
        ///#   #   ###   #  #
        ///#   #         #  #
        ///##################.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 10
        ///##################
        ///#  ## ##   #     #
        ///#  ##  #   ####  #
        ///#          #     #
        ///#   ##   ###  ## #
        ///#                #
        ///#   ###       #  #
        ///#          #  #  #
        ///#    #     #     #
        ///#    #   ###   ###
        ///#                #
        ///#    #     #  ####
        ///#  ###     #     #
        ///#          #   ###
        ///# #        #     #
        ///###     ##########
        ///#               P#
        ///##################.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 10
        ///##################
        ///#    #  #        #
        ///#    #  #        #
        ///#    #  ####     #
        ///#    #  #        #
        ///#                #
        ///#########   ##   #
        ///#                #
        ///#### P       #   #
        ///#            #   #
        ///#  #           ###
        ///#  #             #
        ///#  #         ##  #
        ///#       #    #   #
        ///# ##    #        #
        ///#    ## #  ####  #
        ///#  #        #    #
        ///##################.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 10
        ///##################
        ///#  ##   P#       #
        ///#   #    #       #
        ///#     #  #       #
        ///#                #
        ///#               ##
        ///#   #   ####  #  #
        ///#   #         #  #
        ///#   #      #  ####
        ///#   #      #     #
        ///#             ####
        ///#                #
        ///#######       ## #
        ///#       ##       #
        ///#        #    #  #
        ///#     #####   # ##
        ///#        #    #  #
        ///##################.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tank {
            get {
                object obj = ResourceManager.GetObject("Tank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3 4
        ///################
        ///#P             #
        ///#              #
        ///#              #
        ///#              #
        ///#              #
        ///#              #
        ///################.
        /// </summary>
        internal static string testmap {
            get {
                return ResourceManager.GetString("testmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 17 2
        ///################
        ///#              #
        ///#       ########
        ///#              #
        ///#              #
        ///#####          #
        ///#              #
        ///#              #
        ///#              #
        ///#              #
        ///#              #
        ///#      #########
        ///#              #
        ///#      #       #
        ///#      #      P#
        ///################.
        /// </summary>
        internal static string testmap2 {
            get {
                return ResourceManager.GetString("testmap2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 2
        ///################
        ///#              #
        ///#              #
        ///################
        ///#      P       #
        ///#              #
        ///#              #
        ///################.
        /// </summary>
        internal static string testmap3 {
            get {
                return ResourceManager.GetString("testmap3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wall {
            get {
                object obj = ResourceManager.GetObject("Wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
